# -*- coding: utf-8 -*-
"""Spectral plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiYXgXGODnAC7IcATeNzawdFIdNGhmoh
"""

import matplotlib.pyplot as plt
import csv


def mouse_move(event):
  x, y = event.xdata, event.ydata
  print(x, y)

def main():
  data_path = '20200701/GNBP-10xDilution.csv'

  wv = []
  od = []

  file = open(data_path)
  data = csv.reader(file, delimiter=',')
  real_data = [row for idx, row in enumerate(data) if idx in range (19,1420)]

  for i in range(len(real_data)):
    wv.append(float(real_data[i][0]))
    od.append(float(real_data[i][1]))

  print(len(real_data))
  print(len(wv))
  print(len(od))

  plt.plot(wv,od)
  plt.xlabel('wavelength')
  plt.ylabel('optical density')
  plt.show()
  plt.connect('motion_notify_event', mouse_move)

if __name__ == '__main__':
    main()
